### PR TITLE
fix my issues

### LINKED ISSUE #5: Text not shown for mobile users
See message on Discord [here](https://discord.com/channels/1074965020108136530/1168208717280456735/1186011864803586188).

### LINKED ISSUE #7: reference error
fix navigator reference error + hiftie you should just hard reset to before and squash and merge after

### PR DESCRIPTION
**Pull request by ghost**
fixes #7 
fixes #5

### CODE REVIEW

**Comment by ghost** [comment]
ugh

**Comment by ghost** [comment]
ok i setup vercel on my fork so

**Comment by ghost** [comment]
yea @hiftea you should def squash and merge this. ima fix the other issues and try to be less blind now

**Comment by ghost** [comment]
that should fix it. probably will revert the button changes

**Comment by kxnalpk** [comment]
👍squashed and merged

**Pull request merged**
